### ISSUE TITLE
Featuring/Sync-to-post checklist

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#157]
- [x] fix artist mention from artworks
- [x] sync to post reposts to gallery prof
- [x] STP features to artist/artworks pages
- [ ] tags get auto-associated from artists & artworks (feature to)
- [ ] articles that were features after-the-fact should sync up
